version: '3.7'

services:
  db:
    image: mysql:8
    container_name: db_server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: progetto_db
      MYSQL_USER: utente
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Aggiungi persistenza per i dati MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_server
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: w_server
    volumes:
      - ./web:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:  # Definisci il volume per la persistenza dei dati